### ISSUE TITLE
Can't add a folder

### ISSUE THREAD

**Issue by sebastianstucke87** [ViscousPot/GitSync#26]
**Android 13**

Steps:
1. Installed App via PlayStore
2. Allowed notifications
3. Added auth w/ GitHub
4. Added a folder "GitSync"
5. `Allow Git Sync to access files in GitSync?` -> ALLOW
6. `Inaccessible! Please select a different directory.`

> ![Screenshot_20241117-203925](https://github.com/user-attachments/assets/cb0e14d9-7539-4c52-b49f-dcee72033fd0)

> ![Screenshot_20241117-203818](https://github.com/user-attachments/assets/0912250c-50f1-4fa8-9845-fb4c2a9da3d3)

> ![Screenshot_20241117-203903-943](https://github.com/user-attachments/assets/511eb3eb-09a7-414e-abb9-664be1d3f42b)

**Comment by TheJustNatan** [comment]
got past that be setting it somewhere else like documents

**Comment by sebastianstucke87** [comment]
@TheJustNatan Thank you, that worked! 

I have set it to: `/storage/emulated/0/Documents/GitSync`

**Comment by ViscousPot** [comment]
Hey, glad you got this sorted! 
Going to close this as resolved for now, but feel free to suggest anything I can do to improve this experience.

**Comment by ViscousPot** [comment]
Hey, glad you got this sorted! 
Going to close this as resolved for now, but feel free to suggest anything I can do to improve this experience.

**Comment by Kageetai** [comment]
Hey, just got the same error as the others above before.
So it's not possible to use a newly created folder inside the root folder?

**Comment by ViscousPot** [comment]
It was previously not possible to use a folder in the root folder and some other restricted locations.

**As of v1.609, you can select any folder anywhere.** 
If you are downloading releases on Github, please make sure to select the all-files-access variant (this will be removed to have a single release APK in future)
