### ISSUE TITLE
Feature Request: Device-specific ignore list

### ISSUE THREAD

**Issue by Kageetai** [ViscousPot/GitSync#29]
Hey there,
thanks for this nice little app.
I like the `.gitignore` feature, but instead of using the shared `.gitignore` file, that will also end up on other devices, would there be a way to a something like a "device-specific ignore list", meaning one that only applies on the local device?
This would be useful, as I want different to be able to have different settings per device, e.g. Obsidians active plugins.

**Comment by ViscousPot** [comment]
Hi! I'm not sure I'm totally understanding the request.
A .gitignore file is part of the way git works. I think you should be able to achieve device specific settings by adding the `.obsidian` folder to your .gitignore. You should also be able to get a bit more granular by adding specific plugin settings files (also in the `.obsidian` folder) to the .gitignore. 

Hope that makes sense :)
Let me know if I've misunderstood the request

**Comment by Kageetai** [comment]
Sorry, I guess I should have been more specific.
I have three devices I wanna sync, between two of them I want full sync and backup (also use my git repo as my main backup), meaning all the same plugins active etc. But on my phone I don't want the same Obsidian plugins active etc.
Therefore just adding the `.obsidian` folder (or other files inside) to the gitignore is not an option, as that would mean not backing everything up as well etc.

**Comment by ViscousPot** [comment]
Does[ this feature of git](https://medium.com/@dave_lunny/exclude-files-from-git-without-committing-changes-to-gitignore-986fa712e78d#:~:text=My%20co-worker,see%20or%20touch!) sound like what you are trying to achieve? 

I can add the ability to edit this file in the settings.
I'd prefer to not add any custom logic to the git operations themselves because that might become hard to maintain over time.

**Comment by Kageetai** [comment]
Interesting, I wasn't aware of that feature, might just be what I need then. And yes would be nice to be able to edit that directly in the app.

**Comment by ViscousPot** [comment]
Honestly, nor was I until I came across it while doing research :)

Will add this feature to my list

**Comment by ViscousPot** [comment]
Latest release adds this feature!

https://github.com/ViscousPot/GitSync/releases

**Comment by Kageetai** [comment]
> Latest release adds this feature!
> 
> https://github.com/ViscousPot/GitSync/releases

Thanks a lot, I will try it out
