### ISSUE TITLE
Error when cloning

### ISSUE THREAD

**Issue by saulshanabrook** [ViscousPot/GitSync#36]
I am trying to clone a private repo to a Notes folder in my Documents, but I am encountering the following error: "Failed to clone repository! Operation not permitted" in the middling of the clone. 

I have tried it with the latest version in the app store and also the more recent apk from GitHub. 

Let me know if there is other info that would be helpful. 

Thank you for working on this app!

**Comment by ViscousPot** [comment]
Hi!

Thanks for reaching out. If you are able to recreate the error, could you click on the resulting error notification to send a bug report by email with more details and some logs? From there I can have a better look to figure out what's going wrong. Would love to get this fixed for you :)

Thanks!


________________________________
From: Saul Shanabrook ***@***.***>
Sent: Sunday, November 24, 2024 6:55:14 PM
To: ViscousPot/GitSync ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ViscousPot/GitSync] Error when cloning (Issue #36)


I am trying to clone a private repo to a Notes folder in my Documents, but I am encountering the following error: "Failed to clone repository! Operation not permitted" in the middling of the clone.

I have tried it with the latest version in the app store and also the more recent apk from GitHub.

Let me know if there is other info that would be helpful.

Thank you for working on this app!

**Comment by KGDavidson** [comment]
Will close soon as there has been no movement on this :)

**Comment by ViscousPot** [comment]
Will close soon as there has been no movement
