### ISSUE TITLE
Doesn't work in repo using SSH URI

### ISSUE THREAD

**Issue by jace** [ViscousPot/GitSync#45]
I'm trying to use GitSync in an Obsidian vault that's using GitHub with an SSH URI that I normally sync using the CLI.

GitSync is unable to sync this repo even though it's been authed with GitHub. The error message is "Transport exception: remote hung up unexpectedly".

![Screenshot_2024-12-09-13-16-42-17_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/user-attachments/assets/d470656b-d47e-453f-ae66-03f0c2492538)

I'd prefer to avoid switching to a https:// URL because that'll require a personal access token at the CLI.

**Comment by jace** [comment]
Just noticed the email bug report was acknowledged. I'll wait for working SSH URI support.

**Comment by ViscousPot** [comment]
SSH support is incoming. Will update this issue when it's here!

Thanks for your patience :)

**Comment by ViscousPot** [comment]
Added in this commit!
https://github.com/ViscousPot/GitSync/commit/27ee90dd09e26ec50c6e2796e07113631d717e1a

Included in the latest release
https://github.com/ViscousPot/GitSync/releases/tag/v1.630
