### ISSUE TITLE
Commit list "<Author> commited <hours> hours ago" overlaps diffstat

### ISSUE THREAD

**Issue by vikdotdev** [ViscousPot/GitSync#46]
![photo_2024-12-09_12-47-13](https://github.com/user-attachments/assets/f90ec8ed-6999-4742-9de1-9802b13aead4)

Version 1.620

**Comment by ViscousPot** [comment]
Thanks for catching this. Will put on my list to fix :)

**Comment by ViscousPot** [comment]
Fixed in this commit! Will be included in an upcoming release
https://github.com/ViscousPot/GitSync/commit/ba3d3b0d8010676c9992c4b1148b9a6c919deaf2

**Comment by ViscousPot** [comment]
Fix included in this release
https://github.com/ViscousPot/GitSync/releases/tag/v1.631
